<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
   
<div class="block bestseller-product">
<div class="block-title">
    <strong><span><?php echo $this->__('Bestseller Products') ?></span></strong>
</div>
    <div class="block-content">
		<ul class="slider7">
		<?php $i=0; foreach ($_products->getItems() as $_product): ?>
    
		<li class="item">
		    
		    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
			<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(55); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
		    </a>
				    
		    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>					        
    
		    <?php echo $this->getPriceHtml($_product, true) ?>
		</li>
		
		<?php endforeach; ?>
		</ul>
    </div>
</div>

<?php endif; ?>
