<?php
/**
 * Kendola Login With Amazon for Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Kendola
 * @package    Kendola_AmazonLogin
 * @author     Oliver Treck, kendola - easy eCommerce <o.treck@kendola.de>
 * @copyright  Copyright (c) 2013 kendola - easy eCommerce (http://www.kendola.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $config = Mage::getStoreConfig('amazonlogin/settings/enabled');
if ($config) { ?>
    <div class="col-2<?php echo (1!=@$this->noclass)?' account-login':''; ?>">
        <div class="buttons-set" style="padding-top: 0; margin: 10px 13px;">
            <button id="LoginWithAmazon" style="border:0;background-color:transparent;cursor:pointer;">
                <img border="0" href="#" alt="Login with Amazon"
                     src="/skin/frontend/metros/jack/images/popupAmazon.png"
                     width="173" height="23" />
            </button>
        </div>
    </div>
<?php } ?>