<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Extensions
 * @package     Ma2_PopupLogin free
 * @copyright   Copyright (c) 2013 MagenMarket. (http://www.magenmarket.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: popuplogin.phtml 4 2013-11-05 07:30:56Z linhnt $ */
?>

<div id="ma2popuplogin_src"  style="display:none;">
	<div  id="tab-form-login" class="tab-container" style="display:block;">
			<?php
				 echo $this->getLayout()->createBlock('customer/form_login')->setTemplate('ma2_popuplogin/form/login.phtml')->toHtml();
				?>
		</div>

</div>
<script type="text/javascript">

//<![CDATA[
	function openMyPopup(){
    var win = Dialog.info($('ma2popuplogin_src').innerHTML, {
			className:"ma2_popup magento",
			id:"ma2popuplogin_new",
			closable:false,
			resizable:false,
			draggable:false,
			windowClassName:"ma2_popup_login",
			width:184,
			minHeight:230,
			maxHeight:230,
			recenterAuto:false,
			zIndex:1000,
            onShow: function(){
                $('overlay_modal').setAttribute("onclick","Windows.close('ma2popuplogin_new', event)");
                left = jQuery('.header-container .quick-access .links .last').offset();
                positionLeft = left.left - 80;
                $('ma2popuplogin_new').style.left = positionLeft + 'px';
            },
		});
    
		if($$('#tabsLoginRegister .tab'))
		{
			$$('#tabsLoginRegister .tab').each(function(item){
				item.observe('click', function(event){
					var tabContainer = item.next('dd');
					var pwindowHeight = event.target.measure('height');
					if(tabContainer){
						$$('#tabsLoginRegister .tab').each(function(item){
							item.removeClassName('active')
						});
						$$('#tabsLoginRegister dd').each(function(item){
							item.hide()
						});
						item.addClassName('active');
						tabContainer.show();
						pwindowHeight += tabContainer.measure('height');
					}
					Windows.focusedWindow.setSize(368, pwindowHeight+3);
					Windows.focusedWindow._center();
				});

			});

		}
	}
// ]]>
</script>