<?php
/**
 * Shop By Brands
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitmanufacturers
 * @version      3.3.1
 * @license:     sQl9Zt8K5bexz8avttVeuLMWc01LOvMh5Mmse4lAn8
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
/**
* @copyright  Copyright (c) 2009 AITOC, Inc. 
*/
?>
<?php $manufacturer = $this->getManufacturer() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="category-head">
<h2><?php echo $manufacturer->getManufacturer()?></h2>
</div>
<?php if ($image = $manufacturer->getImage()): ?>
<img src="<?php echo Mage::helper('aitmanufacturers/image')->getUrl($image) ?>" alt="<?php echo $this->htmlEscape($manufacturer->getTitle()) ?>" title="<?php echo $this->htmlEscape($manufacturer->getTitle()) ?>" style="float: left; padding: 0 10px 10px 0" />
<?php endif ?>
<?php if ($content = $manufacturer->getContent()): ?>
<?php echo $content ?>
<br /><br />
<?php endif ?>
<div style="clear:both;"></div>
<?php if ($productList = $this->getChildHtml('product_list')): ?>
    <?php echo $productList;?>
<?php else: ?>
    <?php echo Mage::helper('aitmanufacturers')->__('There are no products matching the selection.') ?>
<?php endif ?>