<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$imageUrl = $this->helper('catalog/image')->init($_product, 'image');
if ($this->getMaxWidth() || $this->getMaxHeight()):

	$imageUrl
		->keepAspectRatio(true)
		->keepFrame(false)
		->constrainOnly(true)
		->resize($this->getMaxWidth(), $this->getMaxHeight());
endif;
$products = Mage::getModel('productvideo/productvideo')->getCollection()
			  		->addFieldToFilter('product_id',$_product->getId())
					->addFieldToFilter('base_image',1)
					->load();
							
			
// IFrame code 
// -See Indies_Productvideo_Block_Catalog_Product_View_Media_Gallery 
// -Bhupendra
if($products->count() == 1):
	foreach($products as $product):
	
			  switch ($product->getVideoHost()):	
			
			case 1 :
			 			
						 $this->getYoutubeIframe($product->getYoutubeId());
			 		     break;
			 case 2 :
			 
					 	 $this->getVimeoIframe($product->getYoutubeId());
			 		     break;
			 case 3 :
			
			 	 		 $this->getDailymotionIframe($product->getYoutubeId());
						 break;
			 case 4 :
			 	 		$this->getMetacafeIframe($product->getYoutubeId());
			 			break;
			 case 5:
			 	    	$parameter="video=".$product->getYoutubeId();
			 			$path =Mage::getBaseUrl(). 'productvideo/video/video?'.$parameter;
			 		echo "<iframe src='".$path."' width='300px' height='266px'  allowFullScreen='true' frameborder='0'></iframe>"; 
			 			break;
						
	  	 endswitch;
	
	endforeach;

else:

?>


<!--Code For Image Thumbnail -->   	
<div class="product-image">
        <a class="indies_productvideo 43" rel="indies_productvideo" href="<?php echo $imageUrl ?>" title="<?php echo $this->htmlEscape($this->getLabel()) ?>">
        <img id="image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(420,385) ?>"        alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"
        title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" />
        </a>
    <div class="slider10">
        <ul>
			<?php 
				if($_product->getResource()->getAttribute('flourescent')->getFrontend()->getValue($_product)=="Yes"){
					?>
						<li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>ico/flourescent.jpg" /></li>
					<?php
				}
			?>
			<?php 
				if($_product->getResource()->getAttribute('glow_dark')->getFrontend()->getValue($_product)=="Yes"){
					?>
						<li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>ico/glow.jpg" /></li>
					<?php
				}
			?>
			<?php 
				if($_product->getResource()->getAttribute('three_pack')->getFrontend()->getValue($_product)=="Yes"){
					?>
						<li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>ico/3pack.jpg" /></li>
					<?php
				}
			?>
			<?php 
				if($_product->getResource()->getAttribute('nine_inch')->getFrontend()->getValue($_product)=="Yes"){
					?>
						<li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>ico/9inch.jpg" /></li>
					<?php
				}
			?>
			<?php 
				if($_product->getResource()->getAttribute('polymer_clay')->getFrontend()->getValue($_product)=="Yes"){
					?>
						<li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>ico/madeof.jpg" /></li>
					<?php
				}
			?>
        </ul>
    </div>
</div>
<?php endif; ?>


<?php if (count($this->getGalleryImages()) > 0): ?>
	<div class="default-views more-views">
        <div class="slider9">
                <ul>
    			<?php foreach ($this->getGalleryImages() as $_image): ?>
    			
				<?php
					if ($_product->getImage() ==  $_image->getFile())
					continue;
			        $imageUrl = $this->helper('catalog/image')
            		->init($this->getProduct(), 'thumbnail', $_image->getFile());
        
        if ($this->getMaxWidth() || $this->getMaxHeight()):
        
           		 $imageUrl
                ->keepAspectRatio(true)
				->keepFrame(false)
                ->constrainOnly(true)
                ->resize($this->getMaxWidth(), $this->getMaxHeight());
        endif; ?>
    	
        <li>
            <a class="indies_productvideo 12" rel="indies_productvideo" href="<?php echo $imageUrl ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(420,385); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            </a>
       </li>
<?php endforeach; ?>
<!--
   Video Thumbnail
  -See Indies_Productvideo_Block_Catalog_Product_View_Media_Gallery 
  -Bhupendra
 -->
<?php 
       $products = Mage::getModel('productvideo/productvideo')->getCollection()
				  ->addFieldToFilter('product_id',$_product->getId())
			  	  ->load();
				   $count = $products->count();
					
		if($products):
		  foreach($products as $product):
		 	switch($product->getVideoHost()):
				case 1:
						
 				 	 $this->getYoutubebox($product->getYoutubeId(),$product->getLabel(),false);
					 break;
			    case 2:
			    	 $this->getVimeobox($product->getYoutubeId(),$product->getLabel(),false);
                     break;
				case 3:
					 $this->getDailymotionbox($product->getYoutubeId(),$product->getLabel(),false);			
				 	  break;
		 		case 4:
					 $this->getMetacafebox($product->getYoutubeId(),$product->getLabel(),false); 
					 break;
				case 5:
					 $this->getFlashbox($product->getYoutubeId(),$product->getLabel(),false);		   
		     		break;						  
				  endswitch;
				endforeach;
		endif;
 ?>
   
   
 <!-- Arrow Image -->
    </ul>
    </div>
</div>

  <!-- Java Script For Fancy Box --> 
<script type="text/javascript">
//<![CDATA[
jQuery('.indies_productvideo').fancybox(<?php echo json_encode($this->getParams()) ?>);
//]]>
</script>
<?php endif; ?>

