<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');

$imageUrl = $this->helper('catalog/image')->init($_product, 'image');
if ($this->getMaxWidth() || $this->getMaxHeight())
{
	$imageUrl
		->keepAspectRatio(true)
		->keepFrame(false)
		->constrainOnly(true)
		->resize($this->getMaxWidth(), $this->getMaxHeight());
}

?>
<p class="product-image">
	<a class="indies_productvideo" rel="indies_productvideo[gal]" href="<?php echo $imageUrl ?>" title="<?php echo $this->htmlEscape($this->getLabel()) ?>">
		<img
			id="image"
			src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($this->getImageWidth(), $this->getImageHeight())->keepFrame($this->getImageFrame()) ?>"
			alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"
			title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"
		/>
	</a>
</p>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
    <?php
		if ($_product->getImage() ==  $_image->getFile())
			continue;
	
        $imageUrl = $this->helper('catalog/image')
            ->init($this->getProduct(), 'thumbnail', $_image->getFile());
        
        if ($this->getMaxWidth() || $this->getMaxHeight())
        {
            $imageUrl
                ->keepAspectRatio(true)
				->keepFrame(false)
                ->constrainOnly(true)
                ->resize($this->getMaxWidth(), $this->getMaxHeight());
        }
    ?>
        <li>
            <a class="indies_productvideo" rel="indies_productvideo[gal]" href="<?php echo $imageUrl ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
				<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($this->getThumbnailWidth(), $this->getThumbnailHeight())->keepFrame($this->getThumbnailFrame()); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
			</a>
        </li>
    <?php endforeach; ?>
    <?php 
        $products = Mage::getModel('productvideo/productvideo')->getCollection()
			  		->addFieldToFilter('product_id',$_product->getId())
			  		->load();
					$count = $products->count();
					
					if($products)
					{
			  			foreach($products as $product)
						{ if($product->getVideoHost()==1)
							 {
							
							
							?>
							<li><a class="indies_productvideo iframe" rel="indies_productvideo[gal]" title="<?php echo $product->getLabel()?>" href="<?php echo 'http://www.youtube.com/embed/'.$product->getYoutubeId().'?autoplay=1' ?>"><img alt="<?php echo $product->getLabel()?>" src="<?php echo "http://img.youtube.com/vi/".$product->getYoutubeId()."/1.jpg" ?>"/></a></li>
						<?php }
							  else if ($product->getVideoHost()== 2)
							  {
						?>		  
						<li><a class="indies_productvideo iframe" rel="indies_productvideo[gal]" title="<?php echo $product->getLabel()?>" href="<?php echo 'http://player.vimeo.com/video/'.$product->getYoutubeId().'?autoplay=1' ?>"><img alt="<?php echo $product->getLabel()?>" src="<?php
							$imgid = $product->getYoutubeId();
							$hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/$imgid.php"));
							echo $hash[0]['thumbnail_medium']; ?>"/></a></li>
						
						
						<?php	
                              }
							  else if($product->getVideoHost() == 3)
							{?>
						
							<li><a class="indies_productvideo iframe" rel="indies_productvideo[gal]" title="<?php echo $product->getLabel()?>" href="<?php echo 'http://www.dailymotion.com/embed/video/'.$product->getYoutubeId().'?autoplay=1' ?>"><img alt="<?php echo $product->getLabel()?>" src="<?php
							echo ' http://www.dailymotion.com/thumbnail/video/'.$product->getYoutubeId()  ?>"/></a></li>
						
						<?php	
						}
						}
					}
	?>
    </ul>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery('.indies_productvideo').lightBox(<?php echo json_encode($this->getParams()) ?>);

//]]>
</script>
<?php endif; ?>